---
- name: init etcd
  command: /bin/bash
  notify:
    - restart etcd
    - mkdir etcd network fold
    - create etcd network configuration
- name: restart etcd
  service: name=etcd state=restarted
- name: mkdir etcd network fold
  command: etcdctl mkdir {{ etcd_data_fold }}/network
  register: has_fold
  failed_when: "'Key alread exists' not in has_fold.stdout and has_fold.rc != 0"

- name: create etcd network configuration
  command: etcdctl mk {{ etcd_data_fold }}/network/config {{ etcd_network_config_js }}
    
- name: restart master daemons
  command: /bin/true
  notify: 
      - restart kube-apiserver
      - restart kube-controller-manager
      - restart kube-scheduler
      - restart flanneld
- name: restart apiserver
  service: name=kube-apiserver state=restarted enabled=yes

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted enabled=yes

- name: restart scheduler
  service: name=kube-scheduler state=restarted enabled=yes

- name: restart flanneld
  service: name=flanneld state=restarted enabled=yes
